### PR TITLE
feat: add cursor style for img type select

### PR DESCRIPTION
**Pull request by Enoooch**

### CODE REVIEW

**Comment by Mayandev** [comment]
Thx for the contribution :)

**Comment by Mayandev** [comment]
> _No description provided._

I am very sorry, I made a big mistake, it cause the PR was not merged, can you initiate it again?

**Comment by Enoooch** [comment]
I thought you didn't think it was necessary.

**Comment by Mayandev** [comment]
> I thought you didn't think it was necessary.
> 
> Should I make a new one? Could not find a way to reopen this.

Sorry, I clicked the wrong button 🤦‍♂️, you can create a new MR.

**Pull request closed without merging**
